---
- name: Install Kubernetes
  hosts: workers
  remote_user: ubuntu
  become: true
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
    ansible_python_interpreter: /usr/bin/python3

  tasks: 

    - name: install aptitude 
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: apt-get update
      ansible.builtin.apt:
        update_cache: yes  

    - name: install required packages
      apt:
        pkg:
          - python3
          - python3-pip
          - python-pip
          - virtualenv
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - curl
          - gnupg
        state: latest
        update_cache: true

    - name: upgrade pip
      pip:
        name: pip
        extra_args: --upgrade

    - name: install python packages
      pip:
        name: 
        - setuptools 
        - scp 

    - name: download docker apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker to sources.list
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present        


    - name: download kubernetes apt key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add kubernetes to sources.list
      ansible.builtin.apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: install docker packages
      apt:
        pkg:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: swapoff
      shell: |
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: modules-load.d
      shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF

        modprobe overlay
        modprobe br_netfilter

    - name: setup required sysctl parameters
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward                = 1
        EOF

        cat << EOF | tee /etc/sysctl.d/99-kubernetes-cri.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        EOF

        sysctl net.ipv4.conf.all.forwarding=1
        echo "net.ipv4.conf.all.forwarding=1" | sudo tee -a /etc/sysctl.conf

        sysctl --system

    - name: Install CRI
      shell: |
        sudo rm /etc/containerd/config.toml

        cat << EOF | tee /etc/containerd/config.toml
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
          SystemdCgroup = true
        EOF

        systemctl restart containerd

    - name: install kubernetes packages
      apt:
        pkg:
          - kubelet
          - kubeadm
          - kubectl
        state: latest
        update_cache: true

    - name: mark hold
      shell: apt-mark hold kubelet kubeadm kubectl

    - name: copy kube_master_ip from local to worker node
      copy:
        src: /Users/ericmaki/code/tf_kube_cluster/kube_master_ip
        dest: /home/ubuntu
        owner: ubuntu     
        mode: 0755      

    - name: copy public key from local to worker node
      copy:
        src: /Users/ericmaki/.ssh/awsTerraTest
        dest: /home/ubuntu/.ssh
        owner: ubuntu
        mode: 0400

    - name: copy master_join.py from local to worker node
      copy:
        src: /Users/ericmaki/code/tf_kube_cluster/master_join.py
        dest: /home/ubuntu
        owner: ubuntu     
        mode: 0755 

    - name: copy kubeadm join token
      shell: python3 master_join.py

    - name: change permissions on join .sh command
      ansible.builtin.file:
        path: /home/ubuntu/kubeadm_join_command.sh
        mode: 0777
      
    - name: join command
      ansible.builtin.shell: /home/ubuntu/kubeadm_join_command.sh


    - name: open ports
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: open ports Kubernetes API server
      community.general.ufw:
        rule: allow
        port: '6443'
        proto: tcp

    - name: open port kubectl 
      community.general.ufw:
        rule: allow
        port: '8080'
        proto: tcp

    - name: open port kublet api
      community.general.ufw:
        rule: allow
        port: '10250'
        proto: tcp

    - name: open ports Node Port Services
      community.general.ufw:
        rule: allow
        port: '30000:32767'
        proto: tcp

    - name: enable ufw
      community.general.ufw:
        state: enabled



