---
- name: Install Kubernetes
  hosts: master
  remote_user: ubuntu

  tasks:

    - name: download weave net
      shell: "kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml"

    
